server:
  port: 8081

rocketmq:
  # 生产者配置
  producer:
    # 访问密钥
    accessKey: rocketmq2
    # 密钥
    secretKey: 12345678
    # on（解析之后为 true）或者 off（解析之后为 false）
    isOnOff: on
    # 发送同一类消息的设置为同一个group，保证唯一
    groupName: defaultGroup
    # 服务地址
    namesrvAddr: 127.0.0.1:9876
    # 消息最大长度 默认1024*1024(1G)
    maxMessageSize: 1048576
    # 发送消息超时时间,默认3000
    sendMsgTimeout: 3000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
  # 消费者配置
  consumer:
    # 访问密钥
    accessKey: rocketmq2
    # 密钥
    secretKey: 12345678
    # on（解析之后为 true）或者 off（解析之后为 false）
    isOnOff: on
    # 官方建议：确保同一组中的每个消费者订阅相同的主题。
    groupName: defaultGroup
    # 服务地址
    namesrvAddr: 127.0.0.1:9876
    # 接收该 Topic 下所有 Tag
    topics:
      - problem_operation~*
      - order_operation~*
      - courier_operation~*
      - site_operation~*
      - task_topic~*
    consumeThreadMin: 20
    consumeThreadMax: 64
    # 设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1

